app = "hackathon-test"
primary_region = "sea"

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  GOOGLE_CLIENT_ID = "1014448268497-c1k9em1qa9lit89opjrncr5292b2kssr.apps.googleusercontent.com"
  GOOGLE_CLIENT_SECRET = "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"
  BACKEND_URL = "https://hackathon-test.fly.dev"
  FRONTEND_URL = "https://google-calendar-bot-lb7lm5oq.devinapps.com"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
