# fly.toml app configuration file generated for backend-app-ikkjfeex-lively-shadow-8911 on 2025-02-05T13:48:17Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-app-ikkjfeex-lively-shadow-8911'
primary_region = 'sea'

[build]

[env]
  BACKEND_URL = 'https://backend-app-ikkjfeex.fly.dev'
  FRONTEND_URL = 'https://google-calendar-bot-lb7lm5oq.devinapps.com'
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 500

[checks]
  [checks.health]
    port = 8000
    type = 'http'
    interval = '15s'
    timeout = '30s'
    grace_period = '30s'
    method = 'GET'
    path = '/api/health'
    protocol = 'http'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  [vm.network]
    enable_ipv6 = true
    [vm.network.outbound]
      via = ["public-ipv4", "public-ipv6"]
