# fly.toml app configuration file
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "backend-app-ikkjfeex-lively-shadow-8911"
primary_region = "sea"

[build]

[env]
  BACKEND_URL = "https://backend-app-ikkjfeex.fly.dev"
  FRONTEND_URL = "https://google-calendar-bot-lb7lm5oq.devinapps.com"
  PORT = "8000"
  REDIS_HOST = "fly-calendar-bot-redis.upstash.io"
  REDIS_PORT = "6379"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
